# Generated by Django 5.0.3 on 2024-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EC2Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ansible_python_interpreter",
                    models.CharField(default="/usr/bin/python3", max_length=255),
                ),
                ("boto3_installed", models.BooleanField(default=True)),
                ("botocore_installed", models.BooleanField(default=True)),
                (
                    "python3_version",
                    models.CharField(default="Python 3.8", max_length=50),
                ),
                ("firewalld_installed", models.BooleanField(default=True)),
                ("firewalld_started", models.BooleanField(default=True)),
                ("http_open", models.BooleanField(default=True)),
                ("https_open", models.BooleanField(default=True)),
                (
                    "application_git_repo",
                    models.CharField(
                        default="https://github.com/diffior/SeniorExperience",
                        max_length=255,
                    ),
                ),
                (
                    "application_git_branch",
                    models.CharField(default="main", max_length=100),
                ),
                (
                    "scripts_src",
                    models.CharField(
                        default="/Users/chrii/Desktop/MSU-Denver/SeniorExp/AWS/first_playbook.yml",
                        max_length=255,
                    ),
                ),
                (
                    "scripts_dest",
                    models.CharField(
                        default="/home/ec2-user/Scripts/scripts_EC2", max_length=255
                    ),
                ),
            ],
        ),
    ]
